### ISSUE TITLE
Please fix this issue

### ISSUE THREAD

**Issue by ghost** [Technerder/KahootFlooder#1]
https://i.imgur.com/ebz62ZU.png

**Comment by toydotgame** [comment]
Open a Command Prompt window as administrator, and type:
```cmd
python -m pip install selenium
```

Then run `python KahootFlooder.py`; done! (Also remember the other steps in the [README](https://github.com/Technerder/KahootFlooder/blob/master/README.md)!)
<br>
<br>
<br>

###### (Also, a tip: If you want to insert an image in GitHub, remember that GitHub Issues support Markdown!
###### You can type this to insert an image directly into the comment:
```md
![](https://i.imgur.com/ebz62ZU.png)
```
###### ...instead of just putting in the link directly)
